namehash/namekit

README.md, packages/sdk/README.md, pnpm-lock.yaml
This might require some tlc by @djstrong @lightwalker-eth
=> docs(sdk): update readme

api/nameguard/models/checks.py, api/nameguard/models/result.py, api/nameguard/web_api.py
Story details: https://app.shortcut.com/ps-web3/story/22269
Improves some examples.
`@computed_property` cannot have examples, afaik.
```json
{
"rating": "warn",
"risk_count": 2,
"highest_risk": {
"check": "confusables",
"status": "warn",
"message": "string",
"check_name": "string"
},
"name": "vitalìk.eth",
"namehash": "0xd48fd5598e605861cbd8e45419b41b83739bff52eaef0e283181bbe0a43a5b32",
"normalization": "normalized",
"checks": [
{
"check": "confusables",
"status": "warn",
"message": "string",
"check_name": "string"
}
],
"labels": [
{
"rating": "warn",
"risk_count": 2,
"highest_risk": {
"check": "confusables",
"status": "warn",
"message": "string",
"check_name": "string"
},
"label": "vitalìk",
"labelhash": "0x41459971a5b847d0eef67bc11e2845f1074a2aed1ac6a357378b18fba50816e4", …
```
=> feat: [sc-22269] Inconsistent examples in redoc

api/nameguard/web_api.py, packages/sdk/src/index.ts
Story details: https://app.shortcut.com/ps-web3/story/23050
=> feat: [sc-23050] Add a description to each of the paths in the openapi spec of NameGuard

apps/website/src/app/components/Header.tsx
With those changes search is always available in navbar either as a search bar or a magnifying glass icon
=> 23701-change-search-appearing-in-navbar

packages/nameguard-react/src/components/Shield/Shield.tsx, packages/nameguard-react/src/components/icons/Loading.tsx, packages/nameguard-react/src/components/icons/LoadingShieldLarge.tsx, packages/nameguard-react/src/components/icons/LoadingShieldMedium.tsx, packages/nameguard-react/src/components/icons/LoadingShieldSmall.tsx
=> Loading shield animate

README.md
Story details: https://app.shortcut.com/ps-web3/story/22753
=> feat: [sc-22753] Add examples to readme of nameguard

api/pyproject.toml
Story details: https://app.shortcut.com/ps-web3/story/24390
=> feat: [sc-24390] Upgrade python stack to 3.12

apps/nameguard.io/src/app/layout.tsx
Story details: https://app.shortcut.com/ps-web3/story/25273
=> feat: [sc-25273] Add `og:site_name` param to all our landing pages

.changeset/little-ladybugs-invent.md, apps/storybook/.storybook/preview.js, apps/storybook/global.css, apps/storybook/stories/Namekit/Link.stories.tsx, packages/namekit-react/src/components/Link.tsx, packages/namekit-react/src/index.ts
=> feat(namekit-react): link component

apps/storybook/stories/Namekit/Input.stories.tsx, packages/namekit-react/src/components/Input.tsx
This doesn't include a changeset since the original changeset hasn't yet been merged.
=> fix(input): use correct styling and stories

apps/nameguard.io/src/app/components/ContentSections.tsx, apps/nameguard.io/src/app/components/organisms/ChecksSection.tsx, apps/nameguard.io/src/app/components/organisms/DevelopersSection.tsx, apps/nameguard.io/src/app/components/organisms/Footer.tsx
Story details: https://app.shortcut.com/ps-web3/story/25276
=> feat: [sc-25276] Resolve Accessibility Audit Issues On All Landing Pages

api/pyproject.toml
@BanaSeba @djstrong we want to rename the `nameguard/nameguard` repo to `nameguard/namekit`.
=> rename repo path

.changeset/calm-cougars-attack.md, README.md, packages/ens-utils/LICENSE, packages/ens-utils/README.md, packages/ens-utils/package.json, packages/ens-webfont/LICENSE, packages/ens-webfont/README.md, packages/ens-webfont/package.json, packages/nameguard-react/LICENSE, packages/nameguard-react/README.md, packages/nameguard-sdk/LICENSE, packages/nameguard-sdk/README.md, packages/nameguard-sdk/package.json, packages/namekit-react/LICENSE, packages/namekit-react/README.md, packages/namekit-react/package.json
=> chore: tidy up packages

apps/namehashlabs.org/next.config.mjs
Story details: https://app.shortcut.com/ps-web3/story/25311
=> feat: [sc-25311] NameHash Labs - Remove CORS configuration from next.config

.changeset/good-tools-marry.md, .github/workflows/changesets.yml
This PR should force the packages to be published now we're ready to drop them for real on NPM.
=> publish packages

.changeset/good-parents-glow.md, packages/nameguard-react/src/components/GraphemeModal/GraphemeModal.tsx, packages/nameguard-react/src/components/GraphemeModal/LoadingSkeleton.tsx, packages/nameguard-react/src/components/Slideover/Slideover.tsx
=> feat(nameguard-react): add unicode version to grapheme modal

.changeset/big-llamas-wash.md, apps/storybook.namekit.io/stories/Namekit/TextArea.stories.tsx, packages/namekit-react/src/components/Input.tsx, packages/namekit-react/src/components/TextArea.tsx
Story details: https://app.shortcut.com/ps-web3/story/25835
=> feat: [sc-25835] Add Specialized Focus / Hover State for Input Fields with an Error

apps/namehashlabs.org/components/2 - molecules/mobile-menu.tsx
Story details: https://app.shortcut.com/ps-web3/story/25702
=> feat: [sc-25702] Fix X button in NameHash Labs Hamburger Menu

apps/nameguard.io/src/components/molecules/HeroStartCommand.tsx, apps/nameguard.io/src/components/organisms/ReadySection.tsx
Story details: https://app.shortcut.com/ps-web3/story/25691
=> feat: [sc-25691] Remove Transparency Where It Shouldn't Exist

.changeset/sharp-rats-stare.md, apps/namehashlabs.org/components/2 - molecules/avatar-with-tooltip.tsx, apps/namehashlabs.org/package.json, packages/namekit-react/src/components/Tooltip.tsx, pnpm-lock.yaml
Story details: https://app.shortcut.com/ps-web3/story/25834
=> feat: [sc-25834] Remove react-tooltip dependency

.changeset/smart-hats-rescue.md, packages/namegraph-sdk/src/index.ts
This PR addresses the addition of the following items:
- `/find_collections_by_collection` NameGraph endpoint
- All interfaces related to it
The interfaces were mirrored from the following reference:
- http://100.24.45.225/docs
=> feat: [SC-25948] ✨ Add new endpoint to NameGraph: findCollectionsByCollections

.changeset/wicked-fishes-cheer.md, packages/namegraph-sdk/src/index.ts
This PR addresses the addition of the following items:
- `/count_collections_by_member` NameGraph endpoint
- All interfaces related to it
The interfaces were mirrored from the following reference:
- http://100.24.45.225/docs
=> feat: [SC-25948] ✨ Add new endpoint to NameGraph: countCollectionsByMember

packages/namegraph-sdk/src/index.ts
Story details: https://app.shortcut.com/ps-web3/story/25962
=> feat: [sc-25962] Setup api.namegraph.dev

packages/namerank-sdk/.gitignore, packages/namerank-sdk/package.json, packages/namerank-sdk/src/index.test.ts, packages/namerank-sdk/src/index.ts, packages/namerank-sdk/tsconfig.json, packages/namerank-sdk/tsup.config.js, pnpm-lock.yaml
Story details: https://app.shortcut.com/ps-web3/story/25579
=> feat: [sc-25579] Create TypeScript SDK for NameRank API

packages/namegraph-sdk/src/index.ts
Story details: https://app.shortcut.com/ps-web3/story/25967
=> feat: [sc-25967] Refine NameGraph Hosting

packages/namegraph-sdk/src/index.ts
Story details: https://app.shortcut.com/ps-web3/story/25992
=> feat: [sc-25992] Fix use of NameGraph inside of NameKit.io

packages/nameguard-python/poetry.lock, packages/nameguard-python/pyproject.toml
Story details: https://app.shortcut.com/ps-web3/story/25916
https://github.com/namehash/ens-label-inspector/pull/33
=> feat: [sc-25916] Update python code to Unicode 16

apps/namekit.io/src/components/organisms/header.tsx
Story details: https://app.shortcut.com/ps-web3/story/26038
=> feat: [sc-26038] Fix Links on NameKit.io landing page

apps/namekit.io/src/app/explore-web3/page.tsx, apps/namekit.io/src/app/layout.tsx
Story details: https://app.shortcut.com/ps-web3/story/26035
=> feat: [sc-26035] Fix all Metadata for new NameKit.io Landing Page

apps/namekit.io/LICENSE, apps/namerank.io/LICENSE
Story details: https://app.shortcut.com/ps-web3/story/26045
=> feat: [sc-26045] Add LICENSE files

apps/api.namerank.io/README.md
Story details: https://app.shortcut.com/ps-web3/story/25964
=> feat: [sc-25964] Setup api.namerank.io

apps/ensnode.io/src/app/layout.tsx, apps/ensnode.io/src/components/hero-section.tsx
Story details: https://app.shortcut.com/ps-web3/story/26137
=> feat: [sc-26137] Improve ENSNode.io website

internal/internal/src/footer.tsx
Story details: https://app.shortcut.com/ps-web3/story/26329
=> feat: [sc-26329] Add ENSNode to "Products" list in Page Footers

apps/namehashlabs.org/components/1 - atoms/headline-banner.tsx
Story details: https://app.shortcut.com/ps-web3/story/26326
=> feat: [sc-26326] Adjust NHL Announcement Bar

internal/internal/src/footer.tsx
Story details: https://app.shortcut.com/ps-web3/story/26328
=> feat: [sc-26328] Adjust NHL Footer

packages/namegraph-sdk/README.md
Story details: https://app.shortcut.com/ps-web3/story/26072
=> feat: [sc-26072] Detailed documentation for the NameGraph SDK

internal/internal/src/footer.tsx
Story details: https://app.shortcut.com/ps-web3/story/26356
=> feat: [sc-26356] Add ENSRainbow to Footer

apps/nameai.io/app/page.tsx, apps/nameai.io/app/shared-metadata.ts
Story details: https://app.shortcut.com/ps-web3/story/26348
=> feat: [sc-26348] Refine NameAI Tagline

internal/internal/src/footer.tsx
Story details: https://app.shortcut.com/ps-web3/story/26357
=> feat: [sc-26357] Fix link to ENSNode in footer

internal/internal/src/footer.tsx
Story details: https://app.shortcut.com/ps-web3/story/26358
=> feat: [sc-26358] Add NameGraph to products list in footer

apps/namegraph.dev/app/layout.tsx, apps/namegraph.dev/components/tld-select.tsx, apps/namegraph.dev/components/ui/namegraph-icon.tsx
Story details: https://app.shortcut.com/ps-web3/story/26372
=> feat: [sc-26372] Fix NameGraph Mobile Nav Bar

apps/namehashlabs.org/data/ensProfiles.ts
Story details: https://app.shortcut.com/ps-web3/story/26355
=> chore: [sc-26355] Update underlying data of individuals listed in the "Supporters" section of the NameHashLabs.org homepage

apps/namegraph.dev/components/homepage/homepage.tsx, apps/namegraph.dev/tailwind.config.ts
Story details: https://app.shortcut.com/ps-web3/story/26371
=> feat: [sc-26371] Fix Namegraph LP Hero section bug

apps/namegraph.dev/components/homepage/homepage.tsx, apps/namegraph.dev/tailwind.config.ts
Story details: https://app.shortcut.com/ps-web3/story/26378
=> feat: [sc-26378] Fix NameGraph Landing Page Animation

apps/namegraph.dev/app/layout.tsx
Story details: https://app.shortcut.com/ps-web3/story/26375
=> feat: [sc-26375] Optimize NameGraph Logo in top nav bar

apps/namekit.io/src/components/molecules/explore-namegraph-form.tsx
Story details: https://app.shortcut.com/ps-web3/story/26369
=> feat: [sc-26369] Fix NameGraph Teaser on NameKit Landing Page

apps/namekit.io/src/components/organisms/header.tsx
Story details: https://app.shortcut.com/ps-web3/story/26370
=> feat: [sc-26370] Hide links to "Explore Web3" on NameKit landing page

apps/namegraph.dev/app/layout.tsx
Story details: https://app.shortcut.com/ps-web3/story/26383
=> feat: [sc-26383] Namegraph Header refinements

apps/namegraph.dev/components/homepage/homepage.tsx, apps/namegraph.dev/tailwind.config.ts
Story details: https://app.shortcut.com/ps-web3/story/26382
=> feat: [sc-26382] Namegraph hero section refinements

apps/namegraph.dev/components/homepage/homepage.tsx, apps/namegraph.dev/components/utils/writers-block-pill.tsx, apps/namegraph.dev/components/utils/writers-block-pills.tsx
Story details: https://app.shortcut.com/ps-web3/story/26385
=> feat: [sc-26385] Update NameGraph layout

apps/namehashlabs.org/components/3 - organisms/partners-section.tsx
Story details: https://app.shortcut.com/ps-web3/story/26397
=> feat: [sc-26397] partners-page-content-update

apps/namegraph.dev/components/homepage/homepage.tsx, apps/namehashlabs.org/components/1 - atoms/icons/efp-logo.tsx, internal/internal/src/icons/efp-icon.tsx
Story details: https://app.shortcut.com/ps-web3/story/26394
=> feat: [sc-26394] Copy updates namegraph

apps/namegraph.dev/components/collections/search-field.tsx, apps/namegraph.dev/hooks/useAnimatedPlaceholder.ts
Story details: https://app.shortcut.com/ps-web3/story/26395
=> feat: [sc-26395] Search input inspiration ideas

apps/namekit.io/src/components/organisms/services-section.tsx
Story details: https://app.shortcut.com/ps-web3/story/26400
=> feat: [sc-26400] Remove ENSNode panel from Namekit.io

apps/namegraph.dev/app/name/[name]/name-details-page.tsx, apps/namegraph.dev/package.json, apps/namehashlabs.org/package.json, pnpm-lock.yaml
Story details: https://app.shortcut.com/ps-web3/story/26387
=> feat: [sc-26387] Upgrade Eth Identity Kit / EFP integrations

apps/namehashlabs.org/components/1 - atoms/headline-banner.tsx
Story details: https://app.shortcut.com/ps-web3/story/26436
=> feat: [sc-26436] Update NHL banner

apps/namekit.io/src/components/organisms/hero-section.tsx, apps/namekit.io/src/styles/globals.css, apps/namekit.io/tailwind.config.ts
Story details: https://app.shortcut.com/ps-web3/story/26396
=> feat: [sc-26396] Namekit LP Panel

apps/namehashlabs.org/components/2 - molecules/products-section.tsx
Story details: https://app.shortcut.com/ps-web3/story/26427
=> feat: [sc-26427] Fix NHL Products List Links

apps/namehashlabs.org/components/2 - molecules/ENSNodeProductPanel.tsx
Story details: https://app.shortcut.com/ps-web3/story/26422
=> feat: [sc-26422] Fix mobile layout of ENSNode product card

internal/internal/src/footer.tsx
As title suggests, related to [this PR from ensawards](https://github.com/namehash/ensawards/pull/3)
=> chore: Addition of ENSAwards to <Footer/> component
